In [2]:
%matplotlib inline

In [3]:
import matplotlib.pyplot as plt
import numpy as np

In [3]:
mean = np.zeros(2)
n = np.random.multivariate_normal(mean = mean, cov = np.eye(2,2), size =100000)
a = n-mean
b = a.T
mult = (b).dot(a)
#soma = 0
#for x in mult:
#    soma += np.mean(x)
#print(soma/len(mult))
#print(np.mean(mult))
#print(np.linalg.det(np.cov(n)))
print(mult/len(a))
n


[[1.00118207 0.00412619]
 [0.00412619 0.99133893]]


array([[-0.52501791,  0.38886774],
       [-0.90598776,  0.09712226],
       [-1.58681259,  0.00628282],
       ...,
       [ 2.69576881, -0.72759314],
       [-0.38181178, -1.91096019],
       [-0.00672266, -1.98141414]])

In [46]:
mean = np.zeros(2)
n = np.random.multivariate_normal(mean = mean, cov = np.eye(2,2), size =100000)
a = n-mean
#b = a.T
soma = 0
for x in n:
    soma += np.outer(x,x)
print(soma/len(n))
#print(np.mean(mult))
#print(np.linalg.det(np.cov(n)))
#print(mult/len(a))

[[ 1.00069634 -0.00409725]
 [-0.00409725  0.99847454]]
